"""
Windows Platform and Hardware Integration Subsystems.
"""
from __future__ import annotations

from jarvis.platform.autostart import AutostartStatus, get_autostart_status, set_autostart
from jarvis.platform.hotkeys import GlobalHotkeyManager, HotkeyRegistration
from jarvis.platform.windows import (
    INPUT,
    KEYBDINPUT,
    MOUSEINPUT,
    RECT,
    POINT,
    MONITORINFOEXW,
    WindowsPlatformAPI,
    close_window,
    focus_window,
    get_active_window,
    get_monitors,
    get_primary_monitor,
    is_window_cloaked,
    is_window_hung,
    list_windows,
    lock_workstation,
    maximize_window,
    minimize_window,
    platform_win32,
    restore_window,
    send_hotkey,
    send_key_combination,
    send_keystrokes,
    set_window_pos,
    type_unicode_text,
)

__all__ = [
    "GlobalHotkeyManager",
    "HotkeyRegistration",
    "WindowsPlatformAPI",
    "platform_win32",
    "get_monitors",
    "get_primary_monitor",
    "list_windows",
    "get_active_window",
    "set_window_pos",
    "focus_window",
    "minimize_window",
    "maximize_window",
    "restore_window",
    "close_window",
    "send_hotkey",
    "send_key_combination",
    "type_unicode_text",
    "send_keystrokes",
    "lock_workstation",
    "is_window_cloaked",
    "is_window_hung",
    "set_autostart",
    "get_autostart_status",
    "AutostartStatus",
    "INPUT",
    "KEYBDINPUT",
    "MOUSEINPUT",
    "RECT",
    "POINT",
    "MONITORINFOEXW",
]
